#! /bin/bash

usage () {
      echo "$0: a small wrapper to generate a rpm."
      echo "Usage: $0 -d"
}

download () {
    local url=$(grep Source0: jscoverage.spec | awk '{ print $2 }')
    local file=$(echo "${url}" | awk -F/ '{ print $NF }')
    if [ -f "${file}" ]; then
	echo "File already downloaded."
	return
    fi
    wget "${url}"
}

build () {
    root=$(dirname $(readlink -f "$0"))
    dist="${root}/dist"

    mkdir -p ${dist}/{RPMS,BUILD}
    rpmbuild --verbose \
	--define "_sourcedir ${root}" \
	--define "_topdir ${dist}" \
	-bb "${root}/jscoverage.spec"
}

if [ "$1" != "-d" ]; then
   usage
   exit 1
fi

set -e
download
build


